server:
    port: 8000

spring:
    profiles: dev

    datasource:
        # dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dataSourceClassName: org.h2.Driver
        url: jdbc:h2:mem:fmu
        databaseName: fmu
        serverName:
        username:
        password:
        activiti.create.engine: classpath:org/activiti/db/create/activiti.h2.create.engine.sql
        activiti.create.history: classpath:org/activiti/db/create/activiti.h2.create.history.sql
        activiti.create.identity: classpath:org/activiti/db/create/activiti.h2.create.identity.sql

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory