server:
    port: 9090

spring:
    profiles: prod

    datasource:
        #driverClassName: com.mysql.jdbc.Driver
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/fmu
        databaseName: fmu
        serverName:
        username: dbuser
        password: dbpass

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

# LIQUIBASE ({sc-spring-boot-autoconfigure}/liquibase/LiquibaseProperties.{sc-ext}[LiquibaseProperties])

liquibase:
    change-log : classpath:/db/changelog/db.changelog-master.yaml
    contexts : # runtime contexts to use
    default-schema : # default database schema to use
    liquibase.drop-first : false
    enabled : true